[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
crosspoint = "B2V3qSDVknbsfLL1ZGfcRxjQqnvUNRppF76X1YXEPNLF"

[programs.devnet]
crosspoint = "B2V3qSDVknbsfLL1ZGfcRxjQqnvUNRppF76X1YXEPNLF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --manifest-path programs/crosspoint/Cargo.toml"
